# Generated by Django 3.2 on 2022-03-09 21:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_enseignant_etudiantt_option_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiantt',
            name='groupe',
        ),
        migrations.AddField(
            model_name='etudiantt',
            name='classe',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Classe'),
            preserve_default=False,
        ),
    ]
