# Generated by Django 4.2.3 on 2025-09-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_auto_20220309_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='groupe',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='etudiantt',
            name='classe',
            field=models.CharField(max_length=200, verbose_name='Classe'),
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='option',
            name='libelle',
            field=models.CharField(max_length=200, verbose_name='Libelle'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nom_projet',
            field=models.CharField(max_length=200, verbose_name='Titre du Projet'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='nom',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(max_length=200, verbose_name='Prenom'),
        ),
    ]
